---

- include: install-redhat.yml
  when: ansible_os_family == 'RedHat' and not borgmatic_skip_install

- include: install-all.yml
  when: ansible_os_family != 'RedHat' and not borgmatic_skip_install

- include: configure.yml
